name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Make test script executable
        run: chmod +x ./test.sh

      - name: Run tests
        run: ./test.sh
